const userData = [
    {
        id: 1,
        name: 'Isabel Tan Yi Ling',
        email: 'isabeltanyiling@pa.gov.sg',
        designation: {name: "Approving Officer 2", id: 2},
        // designation: 2,
        unit: {name: "Jalan Kayu", id: 1},
        usergroupid: 2,
        usergroup: "Community Development Councils Officer",
        boundary: "North-East CDD",
        division: "Eunos",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 2,
        name: 'Judy Liew',
        email: 'judyliew@pa.gov.sg',
        designation: {name: "Approving Officer 2", id: 1},
        // designation: 1,
        unit: {name: "Jalan Kayu", id: 2},
        usergroupid: 1,
        usergroup: "Community Development Councils Approving Officer",
        boundary: "North-West CDD",
        division: "Yew Tee",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Deactivated'
    },
    {
        id: 3,
        name: 'Robert Goh',
        email: 'robertgoh@pa.gov.sg',
        designation: {name: "Approving Officer 2", id: 2},
        // designation: 2,
        unit: {name: "Bishan-Toa Payoh", id:3},
        usergroupid: 3,
        usergroup: "Constituency Office Approving Officer",
        boundary: "North-West CDD",
        division: "Bishan-Toa Payoh",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 4,
        name: 'Joseph Wong Jun Feng',
        email: 'josephwong@pa.gov.sg',
        designation: {name: "Approving Officer 1", id: 1},
        // designation: 1,
        unit: {name: "Yio Chu Kang", id:4},
        usergroupid: 4,
        usergroup: "Constituency Office Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 5,
        name: 'Geraldine Ang',
        email: 'geraldineang@pa.gov.sg',
        designation: {name: "Approving Officer 1", id: 1},
        //designation: 1,
        unit: {name: "Ang Mo Kio-Hougang", id: 5},
        usergroupid: 1,
        usergroup: "Community Development Councils Approving Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 6,
        name: 'Kelly Pang Jia Hui',
        email: 'kellypang@pa.gov.sg',
        designation: {name: "Approving Officer 1", id: 1},
        // designation: 1,
        unit: {name: "Cheng San-Seletar", id: 6},
        usergroupid: 2,
        usergroup: "Community Development Councils Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Deactivated'
    },
    {
        id: 7,
        name: 'Reuben Teo',
        email: 'reubenteo@pa.gov.sg',
        designation:{name: "Approving Officer 2", id: 2},
        //designation: 2,
        unit: {name: "Jurong-Clementi", id: 7},
        usergroupid: 3,
        usergroup: "Constituency Office Approving Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 8,
        name: 'Jane Toh',
        email: 'janetoh@pa.gov.sg',
        designation: {name: "Approving Officer 1", id: 1},
        //designation: 1,
        unit: {name: "Marsiling-Yew Tee", id: 8},
        usergroupid: 4,
        usergroup: "Constituency Office Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Deactivated'
    },
    {
        id: 9,
        name: 'Sam Lim Teo Heng',
        email: 'samlim@pa.gov.sg',
        designation: {name: "Approving Officer 2", id: 2},
        // designation: 2,
        unit: {name: "West Coast", id: 9},
        usergroupid: 1,
        usergroup: "Community Development Councils Approving Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 10,
        name: 'Gerald Toh Yi Xuan',
        email: 'geraldtoh@pa.gov.sg',
        designation:{name: "Approving Officer 1", id: 1},
        //designation: 1,
        unit: {name: "Tanjong Pagar", id: 10},
        usergroupid: 2,
        usergroup: "Community Development Councils Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    },
    {
        id: 11,
        name: 'Elon Mask',
        email: 'elonmask@pa.gov.sg',
        designation: {name: "Approving Officer 2", id: 2},
        //designation: 2,
        unit: {name: "Eunos", id: 1},
        usergroupid: 3,
        usergroup: "Constituency Office Approving Officer",
        boundary: "North-West CDD",
        division: "West Coast",
        committee: "Residents' Committee",
        volunteer: 'NA',
        othergroup: 'Association of Nanyang University Graduates',
        status: 'Activated'
    }
]


  export function getEditUserById(userId) {
    var userInformation = userData.find(e => e.id === userId);
    return userInformation;
}  
